[package]
name = "qrwatermark"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.2"
imageproc = "0.25.0"
qrcodegen = "1.8.0"
rusttype = "0.9.3"

[lib]
crate-type = ["rlib", "cdylib"]

[profile.release]
lto = true
